# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
        alias: common
      - id: end-of-file-fixer
        alias: common
      - id: trailing-whitespace
        alias: common
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        name: 'ruff fix imports'
        args: ["--select", "I", "--fix"]
      - id: ruff
        name: 'ruff (standard)'
      - id: ruff-format
