version: '3.9'

services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: thenewboston
      POSTGRES_USER: thenewboston
      POSTGRES_PASSWORD: thenewboston
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    environment:
      THENEWBOSTON_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
      THENEWBOSTON_SETTING_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'
      THENEWBOSTON_SETTING_CHANNEL_LAYERS: '{"default":{"CONFIG":{"hosts":[["redis", 6379]]}}}'

volumes:
  postgresql-data:
    driver: local
  redis-data:
    driver: local
